import { Geist, Geist_Mono } from "next/font/google";
import ".././globals.css";
import RightSidebar from "@/components/RightSidebar";
import LeftSidebar from "@/components/LeftSidebar";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
         <div className='flex justify-between max-w-6xl mx-auto'>
                <div className='hidden sm:inline border-r-2 border-black/20 h-screen sticky top-0'>
                  <LeftSidebar />
                </div>

                <div className='w-2xl flex-1'>{children}</div>
                <div className='lg:flex-col p-3 h-screen border-2 border-black/20 hidden lg:flex w-[24rem]'>
                  <RightSidebar />
                </div>
              </div>
      </body>
    </html>
  );
}
